### ISSUE TITLE
Issues when trying to build latest version

### ISSUE THREAD

**Issue by wserr** [artempyanykh/marksman#102]
Repro steps:

1. Pull latest main branch
2. In root folder, run `make install`

Error:
```
/home/willem/repos/marksman/Marksman/Config.fs(25,29): error FS0505: The member or object constructor 'TryToModel' does not take 1 argument(s). An overload was found taking 4 arguments. [/home/willem/repos/marksman/Marksman/Marksman.fsproj]
/home/willem/repos/marksman/Marksman/Config.fs(27,37): error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved. [/home/willem/repos/marksman/Marksman/Marksman.fsproj]
```

NOTE: running on dotnet SDK 6.0.110, changed the `global.json` accordingly

NOTE 2: when checking out commit ab5a2c266a00aab9475cc93e47dea1c47ea8d167 (oct 12 2022), the build succeeds

**Comment by artempyanykh** [comment]
First thought - since CI is green perhaps it's some minor incompatibility between dotnet versions. I'll look into it.

@wserr is there a reason you want to use 6.0.101 instead of 6.0.300?

**Comment by wserr** [comment]
@artempyanykh when I try to run following command on ubuntu:

```
sudo apt install dotnet-sdk-6.0
```

I see the following message

```
dotnet-sdk-6.0 is already the newest version (6.0.110-0ubuntu1~22.04.1)
```

**Comment by wserr** [comment]
Tried to install via the dotnet website, instead of the `apt` package manager. Now on dotnet 6.0.402 and now it seems to work. Will close the ticket. Thanks for the quick response though!
