### ISSUE TITLE
“marksman” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by ckipp01** [artempyanykh/marksman#106]
Hello! After updating MacOS today I started to get an error every time I open Neovim and try to use Marksman in a markdown file. I'm greeted with this thing:

<img width="251" alt="Screenshot 2022-11-09 at 19 36 31" src="https://user-images.githubusercontent.com/13974112/200913305-1e7711cc-2ae5-4900-a6e5-66861bf9cc79.png">

Here's some hopefully useful info:

macOS: Ventura 13.0
shell: fish 3.5.1
install method: download the latest `marksman-macos` and then move it to `~/bin/marksman` and slap it with a `chmod +x`
how i use it: default config with [lsp-config](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#marksman).

Any idea what might be going on or is there more info I could provide you with?

**Comment by keynmol** [comment]
Classic.

```
xattr -d com.apple.quarantine ~/bin/marksman
```

:)

**Comment by ckipp01** [comment]
> Classic.
> 
> ```
> xattr -d com.apple.quarantine ~/bin/marksman
> ```
> 
> :)

Well gosh darn, that worked. Thanks @keynmol!

**Comment by artempyanykh** [comment]
Apple's security measures have been pain for a while. I wonder if there's any way to avoid the popup without spending $99/year on an Apple Developer account?..

Anyhow, @keynmol's solution deserves a note in the README :)
