### ISSUE TITLE
Question: Ignoring .gitignore when checking for files in relative links

### ISSUE THREAD

**Issue by DanRoscigno** [artempyanykh/marksman#113]
Thanks for Marksman, it is really helping me out!

I am working across two repos, "reference-docs" and "tutorial-docs".  

The repos are combined into one directory structure when the docs get built with Docusaurus.

When I am writing in "tutorial-docs" I copy the files from "reference-docs" into tutorial-docs so that I can build the documentation as I am editing.  I have all of the tutorial directories in my `.gitignore`.  Because the reference docs are in .gitignore, Marksman flags links to those docs as non-existent.  Is there a way that I can have Marksman ignore the .gitignore?

Thanks so much!

**Comment by DanRoscigno** [comment]
Based on issue #112 I suspect that I need a `.marksman.toml`, but I do not know what to put in it.  I tried this, but did not see a difference.  

```
[code_action]
root = "/home/droscigno/GitHub/Docs/clickhouse-docs"
```

**Comment by artempyanykh** [comment]
Thanks for the kind words @DanRoscigno! Regarding ignoring the `.gitignore`, one thing that may work is to 
1. create a `.ignore` file, and 
2. add negated ignore patterns there. 
 
E.g. if you have `reference-docs/` in your `.gitignore`, try creating `.ignore` with the following content (note the `!` exclamation mark):
```
!reference-docs/
```

**Comment by DanRoscigno** [comment]
.gitignore works perfectly, thanks very much!
