### ISSUE TITLE
Include `.mdx` files in the pick list and URL checking

### ISSUE THREAD

**Issue by DanRoscigno** [artempyanykh/marksman#114]
Hi Artem,
I have a mix of .md and .mdx files.  When I link to a .mdx file Marksman shows a warning for a non-existent document.  Marksman also does not include the `.mdx` files in the pick list when I start typing the path.  I could not find in your code where the list is restricted to `.md` or I would have tried to write a PR.

I added 'nathom/filetype.nvim', and set .mdx to markdown, so Marksman is in use in the mdx files, but that did not help in getting the mdx files recognized from a link in a .md file.  

Thanks again!

**Comment by artempyanykh** [comment]
@DanRoscigno I didn't know about mdx. Is it https://mdxjs.com/ or something else?

**Comment by DanRoscigno** [comment]
Thanks so much!

**Comment by artempyanykh** [comment]
@DanRoscigno please try the new release and let me know if things work for you.

**Comment by DanRoscigno** [comment]
@artempyanykh , I do not see any difference.  Do I need a `.marksman.toml` at the root of the repo I am working in?  I added one with this content, but that did not change it either:
```
[core]
markdown.file_extensions = ["md", "markdown", "mdx"]
```
