### ISSUE TITLE
add nix flake?

### ISSUE THREAD

**Issue by edrex** [artempyanykh/marksman#118]
@artempyanykh would you be open to a PR starting from https://github.com/artempyanykh/marksman/compare/main...the-mikedavis:marksman:flake + adding a GH action to update deps.nix, to track marksman head via nix? 

Is there a better way to handle the version string than https://github.com/artempyanykh/marksman/commit/0d189d223030bb1d9b0e89be9584b9358f87fa71 (@the-mikedavis)?

## Tasks

- [ ] Rebase
- [ ] Automate [updating deps.nix](https://ryantm.github.io/nixpkgs/languages-frameworks/dotnet/#packaging-a-dotnet-application)
 via a Github action.
- [ ] Handle version string somehow

context: https://github.com/helix-editor/helix/pull/3499#pullrequestreview-1110903627

**Comment by edrex** [comment]
I am wondering if it might be possible to do the deps.nix generation at build time, to avoid the need for a commit bot.

**Comment by edrex** [comment]
nevermind, better to keep it in nixpkgs which has a conventional method for updating deps.nix. https://github.com/NixOS/nixpkgs/pull/193682

**Comment by artempyanykh** [comment]
@edrex thanks for raising this (and closing 😉) I personally don't use nix, but am very open to contributions especially those where validation can be reasonably performed on CI.
