### ISSUE TITLE
Ambiguous link to document X when a document's title is a substring of other titles

### ISSUE THREAD

**Issue by MilanVasko** [artempyanykh/marksman#127]
Hello :slightly_smiling_face:

I'm not sure if this is an edge case or a feature that I don't fully understand, but I'm getting a lot of `Ambiguous link` errors in my notes.

I think it's best to describe it with an example. Let's say my notes contain 3 files.

File `horses.md` contains general info about horses:

```markdown
# Horses
```

File `riding-horses.md` contains a riding manual:

```markdown
# Riding horses
```

And `index.md` links to these two notes:

```markdown
# Index

Read about [[horses]]. Also learn [[riding-horses]].
```

If I open `index.md`, I get an error on `[[horses]]`, saying `Ambiguous link to document 'horses'`. Also, if I display project-wide errors, I can see `Duplicate definition of document Horses` in `horses.md` and `Duplicate definition of document Riding horses` in `riding-horses.md`.

```
index.md:3:12: error: Ambiguous link to document 'horses'
horses.md:1:1: Duplicate definition of document Horses
riding-horses.md:1:1: Duplicate definition of document Riding horses
```

I'd expect not to see any errors in this case, since I don't see the ambiguity (and [Emanote](https://emanote.srid.ca) seems to agree with me).

I use [Kakoune](https://kakoune.org) with [kak-lsp](https://github.com/kak-lsp/kak-lsp) plugin and the following configuration:

```toml
# kak-lsp.toml
[language.markdown]
filetypes = ["markdown"]
roots = [".git", ".marksman.toml"]
command = "marksman"
args = ["server"]
```

Anyway, I observe a similar behaviour when using [Helix](https://helix-editor.com).

For convenience, you can use the following shell commands to create a directory which reproduces this issue.

```sh
mkdir marksman-test
cd marksman-test
printf '# Index\n\nRead about [[horses]]. Also learn [[riding-horses]].\n' > index.md
printf '# Horses\n' > horses.md
printf '# Riding horses\n' > riding-horses.md
touch .marksman.toml
```

**Comment by artempyanykh** [comment]
Thanks for reporting this @MilanVasko! This is definitely a big - link resolution is too lenient. I'll fix it shortly.

**Comment by artempyanykh** [comment]
This should be fixed by #133 and available as part of the [last release](https://github.com/artempyanykh/marksman/releases/tag/2022-12-28). @MilanVasko give it a spin and let me know if this works for you.

**Comment by MilanVasko** [comment]
Thanks for the quick fix @artempyanykh! I can confirm the errors are gone now, I'm closing this 🙂

**Comment by jazmit** [comment]
I'm also getting this error, but this time when the target file contains more than one top level heading ('# Title').  I fixed these files to have only one top-level heading, but it took me quite a while to work out what was going on!
