### ISSUE TITLE
goto definition: overly permissive substring matching

### ISSUE THREAD

**Issue by edrex** [artempyanykh/marksman#135]
Links are currently resolved using a floating substring match, but should only be matching tails, see comments https://github.com/artempyanykh/marksman/pull/117#issuecomment-1359684538

**Comment by edrex** [comment]
@srid

**Comment by artempyanykh** [comment]
@edrex are you running the last version (2022-12-28)? Could you provide an example of what's not working?

**Comment by edrex** [comment]
sorry, no i'm still running 1.0.0, meant to update before filing but i didn't have a chance. I'll close and reopen once I have a chance to test latest.
