### ISSUE TITLE
Wiki links include URL encoding of space character

### ISSUE THREAD

**Issue by Mrcuve0** [artempyanykh/marksman#138]
Hi!
Among other things, I'm starting using marksman as an Obsidian-clone on Neovim: it's amazing! I configured it using the toml file as specified in the readme.md

I noticed that wiki-links referring to files having spaces in their name create links with URL encoded spaces (%20).
This behavior breaks both neovim's *go to definition* and *hover* functionalities (`gd` and `K`), so as Obsidian's links (using the official app).

See the following screenshots:

**While invoking the completion**
![Screenshot from 2023-01-10 21-10-25](https://user-images.githubusercontent.com/36898760/211654494-5113f6b5-d6ef-4953-9768-70c056a778e9.png)

**After confirming the completion**
![Screenshot from 2023-01-10 21-10-45](https://user-images.githubusercontent.com/36898760/211654627-c76ba727-542a-4bb0-b5ae-34f395bac156.png)

**Invoking the completion on Obsidian returns a correct link, w/o URL encoding of the space char**
![Screenshot from 2023-01-10 21-12-16](https://user-images.githubusercontent.com/36898760/211654676-249ffffa-6e57-4e7b-9f6f-9b2c9441e3dc.png)

I hope I'm not missing something from the docs

PS: Thank you for your work, I started recently using Obsidian on Neovim and honestly I'm in disbelief  of what marksman can do. It's even better than some specific plugins, and yours is even an LSP!

**Comment by artempyanykh** [comment]
Thanks for the kind words @Mrcuve0! I think the original motivation for url-encoding parts of wiki-link was to avoid a problem with a '#' sign (or any other punctuation) messing with the format of the wiki link. But we don't need full url-encoding for this, it'd be enough to handle just a specific set of chars.

I'll look into fixing this!

**Comment by artempyanykh** [comment]
Reopening until the next release is out

**Comment by artempyanykh** [comment]
The fixes are in https://github.com/artempyanykh/marksman/releases/tag/2023-01-29 @Mrcuve0 feel free to give it a spin and let me know if this is working fine.

**Comment by Mrcuve0** [comment]
I'm not a markdown power-user so I may not have tested everything, but my issue is solved! Thank you so much!

**Comment by artempyanykh** [comment]
Great! Happy to hear that @Mrcuve0
