### ISSUE TITLE
Go to definition via file link is broken if working directory is not the file directory

### ISSUE THREAD

**Issue by lukepighetti** [artempyanykh/marksman#140]
Given two Markdown files in the same directory, marksman `1.0.0-dbad138`, and helix `22.12 (a4de86e7)`

`~/Documents/NOTES.md`

```md
# Notes

This is a bunch of notes
```

`~/Documents/PEOPLE.md`

```md
# People

This is a bunch of people that are referenced in [[Notes]]
```

If your working directory is `~/Documents`, the file link works as expected

If your working directory is `~`, the file link does not work as expected

**Comment by artempyanykh** [comment]
Thanks for raising this @lukepighetti! I think what you're seeing is this https://github.com/artempyanykh/marksman/pull/110

TL;DR: helix used to report bogus workspace folders which caused large file tree scans, which is not cool. The fix makes workspace detection a bit more conservative, but this is better than the previous behavior.

Does your `~/Documents` folder has a `.marksman.toml` or is under version control?

**Comment by lukepighetti** [comment]
There is no `.marksman.toml` file and it's not under version control

**Comment by artempyanykh** [comment]
@lukepighetti does adding a `.marksman.toml` file help?

**Comment by lukepighetti** [comment]
Yes

**Comment by artempyanykh** [comment]
Ok, glad to hear that!
