### ISSUE TITLE
Release built with dotnet 7 instacrash. Figure out what to do

### ISSUE THREAD

**Issue by artempyanykh** [artempyanykh/marksman#148]
When building release builds with dotnet 7 the resulting binaries insta crash with
```
Unhandled exception: System.ArgumentNullException: Value cannot be null. (Parameter 'method')
   at System.ArgumentNullException.Throw(String)
   at System.ArgumentNullException.ThrowIfNull(Object , String )
   at System.Linq.Expressions.Expression.Call(Expression , MethodInfo, Expression, Expression, Expression)
   at Ionide.LanguageServerProtocol.Logging.Providers.SerilogProvider.getPushProperty[a]() in /Users/arr/dev/marksman/LanguageServerProtocol/FsLibLog.fs:line 425
   at Ionide.LanguageServerProtocol.Logging.Providers.SerilogProvider.SerigLogProvider..ctor() in /Users/arr/dev/marksman/LanguageServerProtocol/FsLibLog.fs:line 557
   at Ionide.LanguageServerProtocol.Logging.LogProvider.knownProviders@593-1.Invoke(Unit)
   at Microsoft.FSharp.Core.OptionModule.Map[T,TResult](FSharpFunc`2, FSharpOption`1) in D:\a\_work\1\s\src\fsharp\FSharp.Core\option.fs:line 53
```

The problem seems to be in Serilog bundled with Ionide.LSP. Serilog uses reflection to acquire methods on a context type:
```
let pushPropertyMethod =
        ndcContextType.GetMethod("PushProperty", [| typedefof<string>; typedefof<obj>; typedefof<bool> |])
```

The release builds use "publish trimmed". It seems that dotnet 7 trims more than dotnet 6:
With dotnet 6 the type has the following methods:
```
ndcContextType = PushProperty, IDisposable, (String,Object,Boolean)
ndcContextType = Push, IDisposable, (ILogEventEnricher)
ndcContextType = Push, IDisposable, (ILogEventEnricher[])
ndcContextType = PushProperties, IDisposable, (ILogEventEnricher[])
ndcContextType = Clone, ILogEventEnricher, ()
ndcContextType = Suspend, IDisposable, ()
ndcContextType = Reset, Void, ()
ndcContextType = GetType, Type, ()
ndcContextType = ToString, String, ()
ndcContextType = Equals, Boolean, (Object)
ndcContextType = GetHashCode, Int32, ()
```

With dotnet 7 the type has fewer methods at runtime:
```
ndcContextType = GetType, Type, ()
ndcContextType = ToString, String, ()
ndcContextType = Equals, Boolean, (Object)
ndcContextType = GetHashCode, Int32, ()
```

I also tried removing `-p:PublishTrimmed=true` but then the binaries crash instantly with a bus error.

**Comment by baronfel** [comment]
Is this a case where the LSP library should be marking something as being used, so that the trimmer doesn't trim? Or is this a Serilog problem?

**Comment by artempyanykh** [comment]
@baronfel based on this Serilog's issue I'd assume that it's Serilog's problem: https://github.com/serilog/serilog/issues/1644 However, unlike in that issue, in my case things work fine with dotnet 6, but not with dotnet 7 🤷‍♂️ So, yeah, it needs a bit more digging.

**Comment by artempyanykh** [comment]
@baronfel FYI I found [this article](https://learn.microsoft.com/en-us/dotnet/core/compatibility/deployment/7.0/trim-all-assemblies) and flipping the TrimMode back to partial helped, so I'm doing the upgrade in #185 

The article says that 

> However, only apps with trim warnings will be affected

but I didn't get any warnings when building with trimming. Not sure what's up.
