### ISSUE TITLE
Drop leading slash from wiki link completions

### ISSUE THREAD

**Issue by edrex** [artempyanykh/marksman#162]
I've been using marksman with `completion.wiki.style = "file-path-stem"` since #117, and it's mostly working for me.

The biggest nit I have is that completion formats links with a leading `/`, which I manually delete each time. I could use `file-stem` but I would like to keep paths. I think the defacto link format for other tools is a full path without a leading slash. Theoretically this could be ambiguous since it looks like a relative path, but in practice I think the other tools interpret them from the project root, or at least fall back to the root if a more local match isn't found.

Proposal: drop the leading slash from the `file-path-stem` style.

**Comment by artempyanykh** [comment]
Thanks for raising this @edrex! I'm fine with it. May need to tune path resolution a bit, but should be an easy change overall.

**Comment by s-cork** [comment]
@artempyanykh in vs code the non-leading slash leads to broken links
hover doesn't work
and neither does ctrl/cmd + click to follow the link

Example heirarchy:

```
folderA
 - foo.md
folderB
 - bar.md
 
```

wiki-linking from bar.md to foo.md leads to `[[folderA/foo]]` which is interpreted as `folderB/folderA/foo`.

**Comment by artempyanykh** [comment]
Thanks for raising this @s-cork ! Could you please open a separate issue for this? I can't tell right away what's different in vscode, but the behavior should be fixed to be uniform accross the editors.
