### ISSUE TITLE
linux-arm64 build error 

### ISSUE THREAD

**Issue by JuanZoran** [artempyanykh/marksman#163]
I just build marksman with README, and I get this error message ... 

system : Ubuntu 22.04 arm64 [chroot in an Android machine]
> /home/zoran/.dotnet/sdk/6.0.406/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1083: The specified RuntimeIdentifier 'linux-' is not recognized. [/tmp/marksman/Marksman/Marksman.fsproj]

**Comment by artempyanykh** [comment]
Thanks for reporting this @JuanZoran!

Could you provide an output of `uname -p`? I think the [arch detection in the Makefile](https://github.com/artempyanykh/marksman/blob/main/Makefile#L36) is not complete (my guess is that on your machine it'd be something like `aarch` rather than `arm`?)

You can also run the following command directly to check if the build works (replace $(DEST) with the directory where you want to put the binary, e.g. `~/.local/bin`):
```
dotnet publish -c Release -r linux-arm64 --self-contained true \
		-p:PublishSingleFile=true \
		-p:PublishTrimmed=true \
		-p:DebugType=embedded \
		-p:EnableCompressionInSingleFile=true \
		Marksman/Marksman.fsproj \
		-o $(DEST)
```

**Comment by JuanZoran** [comment]
Sorry for the wrong machine info...
I just ran `uname -p` and got these outputs:
>  aarch64

I tried the code which you gave, it works well, thank you a lot

**Comment by artempyanykh** [comment]
Ok, cool! Now I need to figure out where to find an aarch64 linux VM to test things out.

**Comment by JuanZoran** [comment]
Thanks a lot for building such a nice lsp, and btw I am glad to help build a better marksman if I can do anything for that...,

I am using a Pc with Ubuntu22.04 amd64, and a Pad with Ubuntu22.04 aarch64(chroot environment), but I know nothing about F# or dotnet ... I am a freshman

**Comment by artempyanykh** [comment]
Cool @JuanZoran! Trying to fix this Makefile issue might be a good first step. Then there are also a few issues labeled with "good first issue" if you want to look into something a bit more coding heavy.

**Comment by JuanZoran** [comment]
Unfortunately, I am **preparing for the opening exam**... so maybe I will read that a few days later...

but if you find something wrong and try to fix that,  you can try to push it to GitHub and notify me, I will try to rebuild and give any outputs in time...

**Comment by mrene** [comment]
`uname -p` returns `unknown` on both x86_64 and aarch64 linux on my side.

**Comment by mrene** [comment]
`uname -p` returns `unknown` on both x86_64 and aarch64 linux on my side (`-p` is marked as non-portable)

`uname -m` however properly returns `x86_64` and `aarch64` on both respective systems.

I tried fixing the Makefile but `make publish` gave me a .net error I'm not familiar with:

```
dotnet publish -c Release -r linux-arm64 --self-contained true \
        -p:PublishSingleFile=true \
        -p:PublishTrimmed=true \
        -p:DebugType=embedded \
        -p:EnableCompressionInSingleFile=true \
        Marksman/Marksman.fsproj
MSBuild version 17.3.2+561848881 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
  670524e-dirty
/nix/store/ahyyjjmnzsdmr7q55xc7hsp23jpg6yh9-dotnet-sdk-6.0.405/sdk/6.0.405/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(157,5): error NETSDK1067: Self-contained applications are required to use the application host. Either set SelfContained to false or set UseAppHost to true. [/home/mrene/marksman/Marksman/Marksman.fsproj]
make: *** [Makefile:72: publish] Error 1
```

**Comment by artempyanykh** [comment]
@mrene `uname -m` sounds good!

Regarding ```
/nix/store/ahyyjjmnzsdmr7q55xc7hsp23jpg6yh9-dotnet-sdk-6.0.405/sdk/6.0.405/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(157,5): error NETSDK1067: Self-contained applications are required to use the application host. Either set SelfContained to false or set UseAppHost to true. [/home/mrene/marksman/Marksman/Marksman.fsproj]
```

This is new to me too, but I think adding `-p:UseAppHost=true` to the command line should help. @mrene could you try? Different sources say that UseAppHost should default to true when used with self-contained deployments (marksman's case), maybe some version-to-version differences 🤷‍♂️
