### ISSUE TITLE
Unable to get working on neovim

### ISSUE THREAD

**Issue by EvanLind** [artempyanykh/marksman#164]
**Logs**
> [START][2023-02-18 02:25:13] LSP logging initiated
> [ERROR][2023-02-18 02:25:13] .../vim/lsp/rpc.lua:733    "rpc"   "marksman"      "stderr"        "[02:25:13 INF] <LSP Entry> Starting Marksman LSP server: {}\n"
> [ERROR][2023-02-18 02:38:55] .../vim/lsp/rpc.lua:733    "rpc"   "marksman"      "stderr"        "[02:38:55 INF] <LSP Entry> Starting Marksman LSP server: {}\n"

After restart lsp server, got error: `Client 1 quit with exit code 143 and signal 0`

**additional information**
- work fine with single file;
- not working on markdown folder;
- the root directory is right;

**Comment by artempyanykh** [comment]
Hi @EvanLind! Could you please provide 
1. `marksman --version`,
2. `nvim --version`,
3. Your OS,
4. What` exactly does't work? Is it an insta-crash or some functionality doesn't work?

Also, it'd be helpful if you could run marksman with verbose output e.g. `marksman server -v 5` (I think the arguments should be configurable in neovim)?

The logs as they are now don't tell much -- if there was an error I'd expect to see a stack trace.

**Comment by EvanLind** [comment]
1. marksman version: 1.0.0-89f73f7
2. neopvim: NVIM v0.8.3
3. OS:  Arch Linux x86_64
4. Kernel:  Linux nova 6.1.10-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 06 Feb 2023 09:28:04 +0000 x86_64 GNU/Linux
5. with `marksman server -v 5`, log output:
> [ERROR][2023-02-19 00:54:23] .../vim/lsp/rpc.lua:733    "rpc"   "marksman"      "stderr"        
> "[00:54:23 INF] <LSP Entry> Starting Marksman LSP server: {}\n"
> [ERROR][2023-02-19 00:54:34] .../vim/lsp/rpc.lua:733    "rpc"   "marksman"      "stderr"        "Unhandled exception: "
> [ERROR][2023-02-19 00:54:34] .../vim/lsp/rpc.lua:733    "rpc"   "marksman"      "stderr"        "System.AggregateException: One or more errors occurred. (MailboxProcessor.PostAndAsyncReply timed out.)\n ---> System.TimeoutException: MailboxProcessor.PostAndAsyncReply timed out.\n   at <StartupCode$FSharp-Core>.$Mailbox.PostAndAsyncReply@418-1.Invoke(FSharpOption`1 res) in D:\\a\\_work\\1\\s\\src\\fsharp\\FSharp.Core\\mailbox.fs:line 419\n   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, b result1, FSharpFunc`2 userCode) in D:\\a\\_work\\1\\s\\src\\fsharp\\FSharp.Core\\async.fs:line 465\n   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\\a\\_work\\1\\s\\src\\fsharp\\FSharp.Core\\async.fs:line 104\n   --- End of inner exception stack trace ---\n   at Ionide.LanguageServerProtocol.Server.startWithSetup[client](FSharpFunc`2 setupRequestHandlings, Stream input, Stream output, FSharpFunc`2 clientCreator, FSharpFunc`2 customizeRpc) in /home/runner/work/marksman/marksman/LanguageServerProtocol/LanguageServerProtocol.fs:line 179\n   at Ionide.LanguageServerPr"
> [ERROR][2023-02-19 00:54:34] .../vim/lsp/rpc.lua:733    "rpc"   "marksman"      "stderr"        "otocol.Server.start@268-2.Invoke(FSharpFunc`2 customizeRpc)\n   at Marksman.Program.startLSP(Int32 verbosity, Boolean waitForDebugger) in /home/runner/work/marksman/marksman/Marksman/Program.fs:line 58\n   at Marksman.Program.lspCommand@87.Invoke(Tuple`2 tupledArg)\n   at FSharp.SystemCommandLine.CommandBuilders.SetHandlerInt@207-2.Invoke(InvocationContext ctx)\n   at System.CommandLine.Invocation.AnonymousCommandHandler.Invoke(InvocationContext )\n   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()\n--- End of stack trace from previous location ---\n   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()\n--- End of stack trace from previous location ---\n   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()\n--- End of stack trace from previous location ---\n   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()\n--- End of stack trace from previous location ---\n   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()\n--- End of stack trace from previous location ---\n   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()\n--- End of stack trace from previous location ---\n   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()\n--- End of stack trace from previous location ---\n   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()\n--- End of stack trace from previous location ---\n   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()\n"

**Comment by artempyanykh** [comment]
Hm, the issue looks similar to #144 with Arch being the common denominator. This is helpful! @EvanLind thanks for the information!

**Comment by artempyanykh** [comment]
Ok, so this just happened to me on MacOS, Emacs + LSP-mode. So, it's not arch or neovim specific. Still not sure how to reliably repro it though.

**Comment by artempyanykh** [comment]
I repro the issue more or less reliably with Emacs + LSP-mode and it looks like a bug in the text sync *in* the LSP-mode client.

I'll do a bit more digging but most likely I'm just going to disable incremental text sync by default given how problematic is has been historically.

**Comment by artempyanykh** [comment]
emacs-lsp issue: https://github.com/emacs-lsp/lsp-mode/issues/4013

**Comment by artempyanykh** [comment]
@EvanLind please try the latest version. Best case - I was right about the text sync and this release will fix the problem for you; otherwise, the new release will output a more helpful crash diagnostics.

https://github.com/artempyanykh/marksman/releases/tag/2023-04-02

**Comment by EvanLind** [comment]
Thank you very much, the issue has been fixed

**Comment by artempyanykh** [comment]
Glad to hear that @EvanLind !
