### ISSUE TITLE
Allow the server to request a particular kind of text sync on initialize

### ISSUE THREAD

**Issue by artempyanykh** [artempyanykh/marksman#187]
https://github.com/sublimelsp/LSP-marksman/pull/14

**Comment by rchl** [comment]
You have suggested

```jsonc
"initializationOptions": {
  "preferredTextSyncKind": 1 | 2 // <Full|Incremental>
}
```

I'm fine with that but another approach I have in mind is too have a boolean that enables incremental updates. The reasoning for that is that it's not likely that another sync kind is gonna be introduced in the future so a toggle should be fine.

If spec introduces another sync kind in the future then my suggested solution could become ambiguous though...

**Comment by artempyanykh** [comment]
Thanks for the input @rchl! The difference seems pretty small, so I'd rather stick to kind values to avoid second guessing / any future issues.

Please, give #193 a try. If it works for you, I'll merge and cut the next release.
