### ISSUE TITLE
Implement 'find references' request for #hashtags

### ISSUE THREAD

**Issue by mr-majkel** [artempyanykh/marksman#194]
Hi, I have marksman Apr 6 version installed, neovim 0.9.0 (stable), and it seems LSP references is not working for #tags (it is working for headers). When directly invoked over a tag with `lua vim.lsp.buf.references()` I get "No references found" message. However, the completion for tags works and it even mentions the correct number of references in the workspace. I'm using the default config from the nvim-lspconfig plugin.

**Comment by artempyanykh** [comment]
Thanks for raising this @mr-majkel! This is expected as I have wired only completion for hashtags into the LSP. All the necessary bits and bobs to support reference requests are there, they just need to be wired in.

**Comment by jiangyinzuo** [comment]
A related PR is here. #159

**Comment by eguiraud** [comment]
Hello, no promises but I'm sorely missing his feature as well and in case I ever get a boring couple of afternoons I could look into implementing what's missing :)

@artempyanykh could you please walk me through what the relevant parts of the code base are?

**Comment by artempyanykh** [comment]
Cool @eguiraud ! I'd go about implementing this feature like this:
1. This is the entry point for find references LSP request: https://github.com/artempyanykh/marksman/blob/main/Marksman/Server.fs#L855-L875
2. The method calls into https://github.com/artempyanykh/marksman/blob/main/Marksman/Refs.fs#L296
3. Tags are a bit different from links, so I would 
  1. implement a new method specific for tags inside `Refs.fs` e.g. `findTagOccurrences` and
  2. call it from `findElementRefs` if `el` is a tag.
4. `findTagOccurrences` could just fold over docs in the `folder` and for each doc pull relevant tag occurrences from doc's index https://github.com/artempyanykh/marksman/blob/main/Marksman/Index.fs#L87 . You might want to add a `filterTags` method to `Index` and use it to filter only those tags that match the name of `el` tag.

Feel free to open a draft PR and ask more questions if something's not very clear.

**Comment by petobens** [comment]
Hi @artempyanykh and @eguiraud this is not implemented yet right? It would be a nice feature to have. Are there plans to do it in the short term? (I would gladly help doing it but I have zero F# skills :( )

**Comment by eguiraud** [comment]
Hi, sorry I have started a second job in the meanwhile which left me negative free time :sweat_smile: I have not made any progress towards this.

**Comment by petobens** [comment]
Thanks @eguiraud for your reply. Do you (or @artempyanykh ) have LSP tag completion working? In the following GIF i've added a tag in my `b.md` (right) file but I cannot seem to get completion for it in my `a.md` file (left). Wiki links work just fine.

![marksmantag](https://github.com/artempyanykh/marksman/assets/2583971/b0e93b7b-277d-4d8f-9208-b91acb779cf8)
