### ISSUE TITLE
The .ignore file is not working.

### ISSUE THREAD

**Issue by EvanLind** [artempyanykh/marksman#199]
Marksman may be indexing files inside the .git folder, causing a long wait time when calling vim.lsp.buf.references(). After deleting the .git folder, everything returned to normal. Then, I added .git to the project's .ignore file based on the README, restored the .git folder for testing, and found that vim.lsp.buf.references() took longer again.

**additional information**
- .git folder size is 425 MiB;
- attachment folder size is 57 MiB;
- md files size is 16 MiB;

**Comment by artempyanykh** [comment]
@EvanLind thanks for reporting this! Could you also tell your `marksman --version`?

**Comment by EvanLind** [comment]
installed version 2023-04-02

**Comment by artempyanykh** [comment]
@EvanLind thanks! I had a look and it's not obvious what the problem might be (or more specifically, ignore handling seems to work fine for me, so it might be something else).

I need to ask a few more questions:
1. Do you have `.marksman.toml` at the project root?
2. When you remove `.git` does `vim.lsp.buf.references()` give you cross-file references?
3. How many `.md` files do you have inside your workspace?

Ideally, if you know how to check LSP debug out of neovim, would be great to see a debug log (you'd need to run `marksman` with args `server -v=4`)

(Just a hunch, but it may be that you're impacted by #197. If so, the good news is that it shouldn't be too hard to fix, and unless someone submits a patch I was planning to look into it sometime over the weekend).

**Comment by EvanLind** [comment]
1. The project folder does not include the .marksman.toml file；
2. No cross-file references;
3. 952 .md files;

log:
> [ERROR][2023-04-20 15:16:59] .../vim/lsp/rpc.lua:734    "rpc"   "marksman"      "stderr"        '[15:16:59 WRN] <Doc> Unexpected document version: {"newVersion": 88, "currentVersion": 72, "uri": "{ uri =\\n   \\"file:///home/evanlin/Documents/notes_test/test.md\\"\\n  localPath =\\n   \\"/home/evanlin/Documents/notes_test/test.md\\" }"}\n'

**Comment by EvanLind** [comment]
After removing the .git file and adding the .marksman.toml file, executing vim.lsp.buf.references() again took a long time, and result included cross-file references. Therefore, the reason why removing .git resulted in faster execution speed was only because it was a single-file index. I believe the reason for this issue is consistent with [#197 ](https://github.com/artempyanykh/marksman/issues/197) . @artempyanykh

**Comment by artempyanykh** [comment]
@EvanLind if you fancy building Marksman from source, you may want to give #212 a try. I plan to tweak a couple more things in the PR, but already the overall perf improvement is pretty substantial for larger workspaces.

**Comment by artempyanykh** [comment]
The [2023-06-01](https://github.com/artempyanykh/marksman/releases/tag/2023-06-01) version has been released. Feel free to give it a spin!

**Comment by EvanLind** [comment]
Good job，the issue has been fixed
