### ISSUE TITLE
YAML front matter support

### ISSUE THREAD

**Issue by artempyanykh** [artempyanykh/marksman#20]
Looking at my hakyll blog posts (e.g. [this](https://raw.githubusercontent.com/artempyanykh/blog/master/hakyll/posts/2017-10-02-what-is-a-functor-anyway.md)) I see the following structure

```
---
title: [title]
...
---

## Heading 1
## Heading 2
```

Since there's no 1st level heading there's no clash between yaml's title and a potential markdown `# Title`.

I guess the question for me is: in the presence of a front matter do we want to
a) treat front matter's title as a level 1 heading and therefore prohibit the use of `# ...` in the body of the document.
```
---
title: Front matter
---

# I am prohibited <-- this will be flagged as a duplicate title

## Why

## When
```
b) treat front matter's title as a level 0 heading and level 1 headings will be just regular document headings and there can be multiple of those, e.g.
```
---
title: Front matter
---

# What is front matter <-- OK

# Why front matter <-- Also OK
```

**Comment by artempyanykh** [comment]
@keynmol thoughts?

**Comment by luetage** [comment]
My opinion is that a markdown file without a level 1 heading would feel wrong. There should be an option to still use it without showing an error.

**Comment by artempyanykh** [comment]
Support for YAML front matter was enabled in #22. The front matter is parsed but its contents are not interpreted in any way. This will do until we have a good use-case for interpreting the front matter.

**Comment by cyruseuros** [comment]
How about being abble to query it from the cli (it would be nice if we could query links and backlinks too)? Something like what https://github.com/mickael-menu/zk does - giving access to the graph that the zettels form
