### ISSUE TITLE
Is it possible to make automatically new item for list after enter?

### ISSUE THREAD

**Issue by Esnos33** [artempyanykh/marksman#213]
Hi, in obsidian after you start list, the obsidian automatically adds new item after you hit enter at the end of line. Is it possible to implement it in marksman? I'm using helix if that matters.

example of how it would work:

before pressing enter
1. first item |

after pressing enter
1. first item
2. |

**Comment by artempyanykh** [comment]
Thanks for asking @Esnos33! I think this sort of functionality is better left to the editor to handle. In Emacs its Markdown mode does this. In Neovim I use [this plugin](https://github.com/dkarter/bullets.vim). I'd imagine Helix could do the same with a separate plugin?

I think this will happen only if somebody finds a good way to expose this sort of assists via LSP protocol and then puts together a PR.

**Comment by Esnos33** [comment]
@artempyanykh I understand and thanks for answear! As of today there is no plugin system in helix, but maybe someday there will be this functionality in helix.
