### ISSUE TITLE
Url-encode paths dont't work for both mdlink and wikilink.

### ISSUE THREAD

**Issue by EvanLind** [artempyanykh/marksman#215]
Hello there!

Some markdown editor may  url-encode some parts of md link or wiki link, this behavior breaks the marksman lsp functionality(defination, references, etc.).

**Test case**
```markdown
[test](#Test%20test)   --  not work

[[##Test%20test]]  --  not work

[[##Test test]]  --  work
```

**marksman version** 
2023-06-01

**Comment by artempyanykh** [comment]
Thanks for reporting @EvanLind ! #216 should fix the issue.
