### ISSUE TITLE
How do I enable document symbols from headings?

### ISSUE THREAD

**Issue by Galicarnax** [artempyanykh/marksman#226]
I see in the list of features that document symbols from headings are implemented. Yet, I can't get them to work with NeoVim. Even though `marksman` client is attached to the buffer, invoking `Telescope lsp_document_symbols` yields `No results from textDocument/documentSymbol`. Looked through config options, couldn't find anything relevant either.

P.S. I'm on Arch Linux, marksman version 20230605-1.

**Comment by artempyanykh** [comment]
Hi @Galicarnax! Thanks for reporting this. I see another arch-specific report in #227 . Could you try an earlier version from the ['Releases' page](https://github.com/artempyanykh/marksman/releases).

If no dice, please configure marksman to run with verbosity `marksman server -v=5` and share your LSP logs here.

**Comment by Galicarnax** [comment]
I've been using `marksman` for few months already, and this feature did work in earlier versions, but stopped working after one of the latest updates.  I formulated the issue without mentioning that because I thought it is configuration-specific. But, given another report here, it looks like a bug.

**Comment by artempyanykh** [comment]
@Galicarnax I've cut a new release that should fix the problem: https://github.com/artempyanykh/marksman/releases/tag/2023-07-01
Feel free to reopen the issue if something's still not working.
