### ISSUE TITLE
[FR] Add element to list

### ISSUE THREAD

**Issue by Sleepful** [artempyanykh/marksman#237]
would be nice to have `add element to list` code action.

if I have list 
```md
a. 
b. 
c.
```

I want to be able to just do `add element to list` and get the correct letter/number at the current cursor position, I also want the action to refactor the other elements to have correct ordering. If I want to add an item below `b`, I want the LSP to add the item `c.` and I also want the LSP to refactor the `c.` item to a `d.` letter.

Same for numbers/roman numerals

**Comment by artempyanykh** [comment]
Thanks for filing this @Sleepful! I think we've covered this topic in https://github.com/artempyanykh/marksman/issues/213 so I'm going to close now, but feel free to reopen in case I misunderstood something.

**Comment by Sleepful** [comment]
Thank you @artempyanykh , TIL about `bullets.vim`, exciting.
