### ISSUE TITLE
File names are not used in completions even though they are recognized in links (with `wiki.style = "file-stem"`)

### ISSUE THREAD

**Issue by Gelio** [artempyanykh/marksman#255]
Hey! First, thanks for this great LSP! It is the cornerstone of my Neovim/Obsidian workflow.

# Status quo

For Marksman to play nicely with Obsidian, my `.marksman.toml` is:

```toml
[completion]
wiki.style = "file-stem"
```

Links are correctly referenced by their names. For example:

```markdown
I am using [[XState]] for this project.
```

correctly points to `XState.md` and I can go do that file using "Go to reference".

![image](https://github.com/artempyanykh/marksman/assets/889383/e5fbc52c-bd21-47d7-9208-0f16ab00d563)

# Current behavior

When I then ask for completions for `[[XS`, I get nothing.

![image](https://github.com/artempyanykh/marksman/assets/889383/b55e7391-4458-494b-9a2e-3c5dfa654e7b)

This is because `XState.md` does not have an `h1` heading. In Obsidian, file names are used as document titles, so beginning a document with the same heading as the file name is redundant.

When I add the `# XState` heading at the top of `XState.md`, I do get `XState.md` as a suggestion:

![image](https://github.com/artempyanykh/marksman/assets/889383/4b0476c6-ce93-4bca-83e2-29bb63f69335)

# Expected behavior

I would love it if marksman also included file names as completions. In this case, I would want `XState.md` to appear as a completion even if there is no `# XState` at the top of that file.

This would make the link resolution/autocomplete behave the same way. At the moment, the autocomplete does not show completions, but if I type the file name manually, the link is resolved correctly by marksman.

# Related issues

Possibly related to https://github.com/artempyanykh/marksman/issues/122

**Comment by artempyanykh** [comment]
Thanks for reporting @Gelio! I think this is perfectly reasonable and will improve the UX.

**Comment by artempyanykh** [comment]
I think this should be addressed in [2024-12-04](https://github.com/artempyanykh/marksman/releases/tag/2024-12-04). Please, report if something doesn't work as expected.
