### ISSUE TITLE
Word count?

### ISSUE THREAD

**Issue by phelps-sg** [artempyanykh/marksman#260]
Is there any way to get a word count in marksman?  Or is there better done with another plugin?
Thanks in advance for any suggestions.

**Comment by artempyanykh** [comment]
Hi @phelps-sg! Thanks for asking! I think this is something that can and should be done in the editor itself rather than in the LSP server such as Marksman. I'd recommend checking a documentation for your editor on how to get word count.

**Comment by David-Else** [comment]
@phelps-sg I recommend using Pandoc and this filter: https://github.com/pandoc/lua-filters/blob/master/wordcount/wordcount.lua

When that is copied into your Pandoc scripts dir you can use `pandoc filename --lua-filter=wordcount.lua` and get something like:

```
94 words in body
496 characters in body
580 characters in body (including spaces)
```
It is not so simple to do an accurate word count. You might need to strip out markup that is part of your document but not really part of the words you want counting, you need a tool like Pandoc that is aware of that.
