### ISSUE TITLE
Filter out hashtags within an url when listing tags

### ISSUE THREAD

**Issue by petobens** [artempyanykh/marksman#265]
Following my comment https://github.com/artempyanykh/marksman/pull/262#issuecomment-1819612236 if I have an url like `https://docs.google.com/spreadsheets/d/1Rr7GcfjUwhZfylUk0FGL0Et4kYF5etl49OpRwRmhhlg/edit#gid=1116260529&range=D12` marksman will treat this as tag. Is it possible to filter out these cases?

Dunno if there are other edge cases that need futher filtering out.

**Comment by artempyanykh** [comment]
Thanks for reporting @petobens! Yeah, parsing of tags needs to be fixed.
