### ISSUE TITLE
Support relative paths in markdown inline links

### ISSUE THREAD

**Issue by artempyanykh** [artempyanykh/marksman#27]
Currently, marksman supports go-to definition for inline links with absolute paths only (absolute relative to the repo/folder root), e.g.
```md
[title](/path-to-file.md)
```

We should also support relative paths (at least in terms of go-to definition/references) e.g.
```md
[title](./path-to-file.md)
```

**Comment by artempyanykh** [comment]
Hi @tiyn could you provide a specific example of what's not working? Link resolution (go to definition, hover) with relative paths works, so I'd assume you meant the completion in mind?

**Comment by tiyn** [comment]
Yes, sorry for being a bit unclear.
So you're completely right with your assumption.
It is about using the marksman autocompletion.
When i start typing `[title](` then absolute paths are suggested like `/path-to-file.md` this works fine.
Also autocompletion works, when using `#` afterwards - like `[title](/path-to-file.md#` - to get a link to a header.

For relative paths both of this does not work.
When typing `[title](./` nothing further is being suggested by marksman.
After finishing the path to an existing file and starting to type a header - like `[title](./path-to-file.md#` - no completions are suggested.

**Comment by artempyanykh** [comment]
@tiyn right. Yes, this completion functionality got lost after a recent rework. I thought about bringing it back in https://github.com/artempyanykh/marksman/pull/134 but it all was a bit fuzzy. My main concern there was that even if we enable completion on relative paths the completion candidates will have absolute paths, which is a bit inconsistent.

I was thinking about adding a config option to choose between absolute and relative paths in completion; but this doesn't address the problem when paths of mixed styles are used: both relative and absolute.

@tiyn could you elaborate on how you used the completion before with relative paths and also if mixed paths were a problem (ideally, please, put it into a separate issue).

**Comment by tiyn** [comment]
Thats sad to hear, it was probably my most used functionality, but i understand the reasoning.
I think the config for selection would at least make it possible for users like me to use relativ paths exclusively.

I usually use relative paths like `[title](./path-to-file.md)` this.
Links to sections I use like this `[title](./path-to-file.md)#section` and in file links like this `[title](#section)`.

Shall I open a new Issue to adress the completion for relative paths?

**Comment by artempyanykh** [comment]
@tiyn yes, please open an issue. I'm happy to support this functionality. Just need to understand your use case better.
