### ISSUE TITLE
Marksman runs fine on Helix but getting error logs

### ISSUE THREAD

**Issue by Koba0117** [artempyanykh/marksman#289]
I talked about this issue in https://github.com/artempyanykh/marksman/issues/270 but this is probably unrelated to https://github.com/artempyanykh/marksman/issues/270 and my explanation got very long so I opened  a new one.

I use Marksman on Helix and it runs fine but every time I open a markdown file, I get an error in helix.log.
I also get errors when I make references on markdown files.

I checked other LSPs on my computer but I got this issue only with Marksman.

## Opening a markdown file
- Before opening a markdown file
![image](https://github.com/artempyanykh/marksman/assets/112705243/84741b8b-f1c1-4ea5-af03-76758fcec59d)

- After opening a markdown file
![image](https://github.com/artempyanykh/marksman/assets/112705243/2c404b41-30a1-43aa-9b83-e3b7d2ac5601)
``
2024-01-11T21:06:09.526 helix_lsp::transport [ERROR] marksman err <- "[21:06:09 INF] <LSP Entry> Starting Marksman LSP
 server: {}\n"
``

## Restarting LSP
Considering the error message, restarting marksman may make a same error so I did it too.
- Before restarting
![image](https://github.com/artempyanykh/marksman/assets/112705243/970323d5-8e0f-4ebd-9f58-e78c0539a617)

- After restarting
![image](https://github.com/artempyanykh/marksman/assets/112705243/07691164-a73d-4a33-a28d-defd7d17e24f)
``
2024-01-11T21:09:13.114 helix_lsp::transport [ERROR] marksman err <- "[21:09:13 INF] <LSP Entry> Starting Marksman LSP
 server: {}\n"
`` 

 ## Reference 

- Before
![image](https://github.com/artempyanykh/marksman/assets/112705243/a83abbd2-be85-4f04-af34-6ac7731dbd84)

- After
![image](https://github.com/artempyanykh/marksman/assets/112705243/31ba68ec-a97f-4e20-baf4-eff4184809ab)
``
2024-01-11T21:14:24.637 helix_lsp::transport [ERROR] marksman err <- "[21:14:24 WRN] <Doc> Unexpected document version
: {\"newVersion\": 9, \"currentVersion\": 4, \"uri\": \"file:///home/kyosuke/Documents/marksman-test/test.md\"}\n"
``

- Before
![image](https://github.com/artempyanykh/marksman/assets/112705243/6da25d2f-ff43-470e-bf40-7ff31477c2eb)

- After
![image](https://github.com/artempyanykh/marksman/assets/112705243/fa85a074-8ba5-4f6b-9612-f96ec9d6c6f3)
``
2024-01-11T21:19:20.925 helix_lsp::transport [ERROR] marksman err <- "[21:19:20 WRN] <Doc> Unexpected document version
: {\"newVersion\": 52, \"currentVersion\": 47, \"uri\": \"file:///home/kyosuke/Documents/marksman-test/test.md\"}\n"
``

- Before
![image](https://github.com/artempyanykh/marksman/assets/112705243/fbb5e070-dc7d-4b49-8a93-88db6a876aad)

- After
![image](https://github.com/artempyanykh/marksman/assets/112705243/d8c30e54-b05a-422d-a98c-e1ebf4d682e7)
``
2024-01-11T21:28:27.674 helix_lsp::transport [ERROR] marksman err <- "[21:28:27 WRN] <Doc> Unexpected document version
: {\"newVersion\": 117, \"currentVersion\": 112, \"uri\": \"file:///home/kyosuke/Documents/marksman-test/test.md\"}\n"
``

- Even though I got error logs, referencing works without problems.
![image](https://github.com/artempyanykh/marksman/assets/112705243/f2d03fcc-584d-4f77-ae12-346d99a2b84e)

## Comment
I have no idea if this is happening because of  my environment, Marksman or Helix.
If there is any missing information, I'm happy to offer it.

**Comment by artempyanykh** [comment]
```
2024-01-11T21:09:13.114 helix_lsp::transport [ERROR] marksman err <- "[21:09:13 INF] <LSP Entry> Starting Marksman LSP  server: {}\n"
```
This is not an error, this is just Marksman's logging output. I'm not sure why helix marks it with an `ERROR` tag (perhaps, because it comes from stderr?).

```
"[21:28:27 WRN] <Doc> Unexpected document version : {\"newVersion\": 117, \"currentVersion\": 112, \"uri\": \"file:///home/kyosuke/Documents/marksman-test/test.md\"}\n"
```

This is also not an error. I used to have this consistency check but since then realised that none of the editors follow sane document versioning practices. This check (and hence the warning) should no longer be present in the most recent release.

**Comment by Koba0117** [comment]
@artempyanykh 
Thank you so much for your help!
I understand they are not error logs and there is no problem.

> This check (and hence the warning) should no longer be present in the most recent release.

I'm likely using 2023-12-07 version because distro's official repo is still using it. (I flagged it as outdated.)

I was just wondering if those logs caused any problems. So I'm glad to hear that is not the case.
Thank you again for creating this wonderful software!

**Comment by artempyanykh** [comment]
These logs shouldn't cause any problems. And thanks for the kind words @Koba0117!
