### ISSUE TITLE
Where can i find the keybindings for marksman?

### ISSUE THREAD

**Issue by fretzo** [artempyanykh/marksman#304]
Hi, 

quick question: Where can i find the keybindings for marksman?

I am using the plugin in neovim, and i installed it through NixOs system packages, and everything works great!

The only information i have found regarding bindings is [here](https://medium.com/@chrisatmachine/lunarvim-improve-markdown-editing-with-marksman-739d06c73a26).

Is there another place that lists the bindings?

Thank you.

**Comment by skbolton** [comment]
You have to set them up yourself. You can look into `:help lsp` to get the lsp docs in neovim. But generally the functions all start with `vim.lsp....`.

Here is an example from my old dotfiles where I set the callback for a language server attaching to a buffer and setting up keybinds. https://github.com/skbolton/titan/blob/d37c0178c41652191285fe031ca89ee0568c3bf5/nvim/nvim/plugin/lsp.lua#L34

**Comment by artempyanykh** [comment]
Thanks @skbolton for answering the question here!
