### ISSUE TITLE
 Fixing "Link to non-existing heading 'xyz' in document 'abc'" deletes content of  'abc' File.

### ISSUE THREAD

**Issue by forgemo** [artempyanykh/marksman#309]
I'm using the Helix editor with marksman. 
I have the following two files.

`people.md`
```md
# People
## Max
## Judy
```

`note.md`
```md
I met [[people#Bob]]
```

Since Bob doesn't exist, I get the following warning.

![image](https://github.com/artempyanykh/marksman/assets/147808/0981a3be-ede8-4863-8879-a24d33e4e63a)

As a solution, it suggests creating people.md.
![image](https://github.com/artempyanykh/marksman/assets/147808/5e1216df-8971-4ef5-b4d5-de81b8c05a89)

This is obviously misleading, since people.md already exists.

Much worse, however. If I execute the suggested action, the existing `people.md` file get's overwritten and all its content gets deleted.

I'm using marksman version `1.0.0-f124c56+f124c5616cf38241e1a5e58808ed78e2d9a1d385` via Snap on ubuntu.
My Helix is on version `24.3 (1abb64e4)`.

**Comment by artempyanykh** [comment]
Thanks for reporting the problem @forgemo! I'd need to see if that's fully on Marksman or there's some weird interaction with Helix. But obviously deleting content is no bueno.
