### ISSUE TITLE
How to ignore a line ?

### ISSUE THREAD

**Issue by samuel-cavalcanti** [artempyanykh/marksman#329]
Hi, is it possible to ignore a line like ?:

 ```md
> this is an info quote
{: .prompt-info }<!-- marksman ignore this line -->
 ```
Because when I format the document the result is:

```md
> this is an info quote
> {: .prompt-info }
```

**Comment by Lamby777** [comment]
Came here from this exact same problem of `.prompt-info` in jekyll lol

**Comment by artempyanykh** [comment]
Hey @samuel-cavalcanti @Lamby777! Could you please elaborate what the problem is? In case it's about formatting, note that Marksman doesn't do formatting, and it might be e.g. prettier (cf. #327).

**Comment by samuel-cavalcanti** [comment]
your are right, it was the prettier.

**Comment by samuel-cavalcanti** [comment]
btw, `<!-- prettier-ignore -->` solve my problem

```md
<!-- prettier-ignore -->
> this is an info quote
{: .prompt-info }
```
