### ISSUE TITLE
When the file contains non-English characters, an error will occur

### ISSUE THREAD

**Issue by im-rinnin** [artempyanykh/marksman#332]
I test chinese/janpenese markdown file name, when i use telescope workspace_symbol both get error

```
测试.md
```

```
Error executing vim.schedule lua callback: ...share/nvim/lazy/telescope.nvim/lua/telescope/pickers.lua:1345: Cursor position outside buffer
stack traceback:
        [C]: in function 'nvim_win_set_cursor'
        ...share/nvim/lazy/telescope.nvim/lua/telescope/pickers.lua:1345: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

**Comment by artempyanykh** [comment]
@im-rinnin are you sure the error is from Marksman? Looking at the backtrace, it looks like it's coming from telescope.

**Comment by im-rinnin** [comment]
> @im-rinnin are you sure the error is from Marksman? Looking at the backtrace, it looks like it's coming from telescope.

sorry it's my problem, vim.buf.lsp.workspace_symbol() is ok
