### ISSUE TITLE
Ability to link to a file with multiple level 1 headings

### ISSUE THREAD

**Issue by oredaze** [artempyanykh/marksman#374]
I use markdown as a note taking tool to provide me with some colors and other such goodies. I do not use it to style web content. My workflow involves my files to all have a bunch of level 1 headings to denote sections, because I don't need a markdown title. My file name is a title. Also typing `#` is better than typing `##`.

However as it stands now I cannot do `[[filename]]` that has a bunch of level 1 headings. With my workflow marksman forces me to do `[[filename#heading]]` else I get "ambiguous link to document" error. Thus I lose functionality.

It would be of great help if you could provide a configuration option that enables `[[this]]` to do dumb linking directly to files, regardless of their heading content.

**Comment by artempyanykh** [comment]
Hi @oredaze! I think this should be addressed in [2024-12-04](https://github.com/artempyanykh/marksman/releases/tag/2024-12-04).

**Comment by oredaze** [comment]
At first glance it is working as expected. Many thanks!
