### ISSUE TITLE
Diagnostics not reported after closing and re-opening a file

### ISSUE THREAD

**Issue by rchl** [artempyanykh/marksman#62]
1. Have some diagnostics visible in a markdown file
2. Close the file
3. Open the same file again

Expected: Same diagnostics shown as before closing the file.

Actual: The diagnostics are not shown after re-opening the file.

**Comment by artempyanykh** [comment]
Thanks for reporting @rchl! I could reproduce the issue.

**Comment by artempyanykh** [comment]
@rchl please try https://github.com/artempyanykh/marksman/releases/tag/2022-08-28 and feel free to reopen the issue if the problem still persists.

**Comment by rchl** [comment]
Looks good. Thanks.
