### ISSUE TITLE
Support Mac Silicon build

### ISSUE THREAD

**Issue by rchl** [artempyanykh/marksman#64]
Is it possible to provide a native mac arm64 build?

**Comment by artempyanykh** [comment]
As soon as Github provides apple silicon runners https://github.com/actions/runner-images/issues/2187 
Until then there's no easy way to do apple silicon builds on CI.

**Comment by rchl** [comment]
OK. Maybe keep it as a feature request (rather than a question)? :)

**Comment by artempyanykh** [comment]
The latest release now includes a **universal** binary for MacOS: https://github.com/artempyanykh/marksman/releases/tag/2022-12-19
