### ISSUE TITLE
Document Symbols Ordering

### ISSUE THREAD

**Issue by n0s4** [artempyanykh/marksman#78]
I have a file like so:

```markdown
# Heading 1

## Subheading 1.1

## Subheading 1.2

# Heading 2 

## Subheading 2.1

## Subheading 2.2
```

When I open the symbol picker I expect the ordering to be top to bottom, but it instead lists H1s first, then H2s:

![sym_picker](https://user-images.githubusercontent.com/96927121/189710276-fc28c37d-6232-44a9-bd09-4b6eb41ffb98.png)

**Comment by artempyanykh** [comment]
Are you using Telescope? On the server side the symbols are produced in the *expected* order and in a hierarchy, but apparently Telescope applies its own ordering on top.

I'd recommend checking Telescope's docs wrt sorters and/or raising an issue there.

**Comment by n0s4** [comment]
No, this is actually Helix's builtin symbol picker (<kbd>Space-s</kbd>). I'm not sure if Helix applies ordering on top. Are you saying that is the likely cause?

**Comment by artempyanykh** [comment]
Ah, OK! Helix doesn't support hierarchical document symbols so there's a flat list which is a different code path. I'm 90% sure that the server still produces symbols in the expected order and it's Helix applying its ordering on top (which looks like alphabetical).

**Comment by artempyanykh** [comment]
@n0s4 turned out the weird ordering was coming from the server. I just pushed a new release with the fix https://github.com/artempyanykh/marksman/releases/tag/2022-09-13
