### ISSUE TITLE
LSP position back to offset

### ISSUE THREAD

**Issue by oovm** [artempyanykh/marksman#8]
I have such a requirement, I need to know what AST node is currently selected by the mouse.

My AST uses offset to store range information.

Because binary search based on offset is easier to write.

The error reporting library [(ariadne)](https://github.com/zesterer/ariadne) I use is also offset based.

So I want an method like the following:

```rs
fn lsp_pos_to_offset(&self, lsp_pos: &lsp_types::Position) -> Option<usize>
```

**Comment by artempyanykh** [comment]
There's a private function that converts `Pos` to byte offset: https://github.com/artempyanykh/zeta-note/blob/main/lsp-document/src/lib.rs#L390-L394

I guess it's OK to expose it as a part of `TextMap` API.

**Comment by artempyanykh** [comment]
I've move `lsp-document` into a separate repo. @oovm feel free to [open an issue there](https://github.com/artempyanykh/rust-lsp-document/issues/new) if this is something you're still interested in.

**Comment by oovm** [comment]
thanks
