### ISSUE TITLE
How to enable/configure single-file mode?

### ISSUE THREAD

**Issue by reagle** [artempyanykh/marksman#86]
The README says the following, but how to enable?

> Marksman has a custom single-file mode that provides a subset of language features for markdown files open outside of any project. This works well for small one-off edits or when opening random markdown files.

**Comment by artempyanykh** [comment]
@reagle single-file mode will be activated by default if the editor supports it. So far, I know that Sublime and Helix do this; while neovim and emacs need a folder.

The README can be improved to make it clearer.

Do you experience problems with single-file mode in one of the supporting editors?

**Comment by reagle** [comment]
In ST4, in the diagnostics panel, I was being shown linting errors for files I didn't have open, so I thought I must've not been in single-file mode.

**Comment by artempyanykh** [comment]
@reagle I see. A single-file mode is not something that currently can be toggled by the user but is rather enabled based on what the editor sends during LSP server initialization. Basically, it was implemented as a fallback mode in cases where the folder is not available to improve the UX.

I think it shouldn't be too hard to make a config option that would force the single file mode regardless of what the editor wants. Although, I do wonder what's the use case and why you would prefer the single file mode when a proper workspace folder is already setup?

**Comment by artempyanykh** [comment]
All right. I think #87 + #88 would be a constructive solution to the problem with potentially #89 to silence diagnostics when it's distracting. I'm going to close this issue for now, but @reagle feel free to re-open if you feel that a single-file toggle would be valuable.
