### ISSUE TITLE
Don't include `source` code action by default

### ISSUE THREAD

**Issue by rchl** [artempyanykh/marksman#90]
Marksman returns code action of the `source` kind (titled `Create a Table of Contents`) when editor asks for code actions without explicitly specifying any `kind`s.

For example editor make this request:

```js
{
  "context": {
    "diagnostics": [],
    "triggerKind": 2
  },
  "range": {
    "end": {
      "character": 0,
      "line": 0
    },
    "start": {
      "character": 0,
      "line": 0
    }
  },
  "textDocument": {
    "uri": "file:///usr/local/workspace/sublime-packages/LSP/README.md"
  }
}
```

and marksman returns:

```js
[
  {
    "edit": {
      "changes": {
        "file:///usr/local/workspace/sublime-packages/LSP/README.md": [
          {
            "newText": "<!--toc:start-->\n- [Installation](#installation)\n  - [Stable Version](#stable-version)\n  - [Development Version](#development-version)\n- [Getting started](#getting-started)\n- [Getting help](#getting-help)\n<!--toc:end-->\n\n",
            "range": {
              "end": {
                "character": 0,
                "line": 0
              },
              "start": {
                "character": 0,
                "line": 0
              }
            }
          }
        ]
      }
    },
    "isPreferred": false,
    "kind": "source",
    "title": "Create a Table of Contents"
  }
]
```

I don't have any explicit description of expected behavior for this but based on VSCode primarily (and what we have mirrored in Sublime Text) it seems that the `source` code actions should not be returned unless specifically asked for by the editor. Not following this logic results in editor providing `source` diagnostics for every location in the file (since editors request diagnostics for the current selection/cursor position) which is non-ideal for those kind of code actions.

(This issue originated from the discussion in https://github.com/sublimelsp/LSP/issues/1846#issuecomment-1255150008)

**Comment by rchl** [comment]
I have tested Volar and Stylelint language servers and both don't provide `source`-level code actions unless explicitly asked for those.

That said, I have tried your VSCode extension for this server and it appears that VSCode itself filters out `source` code actions for the code actions requested for current selection/cursor. So that's why this issue is not visible there. I suppose Sublime Text should also follow that but it wouldn't hurt to also change behavior of this server to avoid extra unnecessary work (providing code action that is anyway filtered out).

**Comment by jwortmann** [comment]
I can't find any hint in the LSP specs which would support this proposition. I think it should be perfectly fine to return "source" code actions, even if some other servers don't do this (perhaps they all use Microsoft's node based language server library which might force this behavior or so).

If it turns out that "source" actions should really not be provided unless explicitly asked for, then this should at least be added to the LSP specs and https://github.com/microsoft/language-server-protocol/issues would be a better place to discuss this first.

**Comment by rchl** [comment]
https://github.com/microsoft/language-server-protocol/issues/1554

**Comment by David-Else** [comment]
I don't have anything to add on the technical side, but from the user side the current behaviour of having a code action to create a table of contents appear everywhere in the file is annoying. 

If I don't want a table of contents I constantly have the little code action light bulb alerting me on every single line to make one. Maybe it should only light up on the first line of the document, as that is where the TOC would be generated? It would also save some CPU?

These light bulbs for code actions are very popular in Neovim, plugins like https://github.com/kosayoda/nvim-lightbulb. I imagine Helix will get something similar at some point as it is a great feature.

**Comment by artempyanykh** [comment]
> Maybe it should only light up on the first line of the document, as that is where the TOC would be generated

Yeah. This would make this feature less discoverable but probably still better overall UX than the current state.

**Comment by artempyanykh** [comment]
#96 should address the annoyance of 'Create ToC' code action. I'm going to close this issue now. Feel free to re-open if there's something else actionable that I missed.

**Comment by jwortmann** [comment]
> I think the explanation from the LSP maintainer at [microsoft/language-server-protocol#1554](https://github.com/microsoft/language-server-protocol/issues/1554) is in line with my suggestion to not return `source` actions unless explicitly asked for.

Hm, I would say that the following quote from https://github.com/microsoft/language-server-protocol/issues/1554#issuecomment-1266512306 seems to indicate the contrary to that:

> So if a client asks for code actions without any kind the standard quick fix code actions should be returned.
>
> If a server returns more code actions (e.g. includes source code actions) clients are allowed to filter them to ensure UI consistency.

I would infer from this, that servers are allowed to return "source" actions even if not explicitly asked for, and that Sublime LSP needs to filter them out afterwards if it wants to make sure that no "source" actions are shown in the UI. Otherwise the answer would be written in a way like this:

> "So if a client asks for code actions without any kind, the server **must only** return the standard quick fix code actions.
> Clients don't need to filter code actions by themselves to ensure UI consistency."

My interpretation is based on the description in https://www.ietf.org/rfc/rfc2119.txt about what words like "must" or "should" mean.

Also, if your interpretation was true, the idea from #96 to return the "Create Table of Contents" action when the curser / requested range is on the first line, would not be allowed then.

**Comment by rchl** [comment]
But the overall summary is that the intention is that the `source` actions are either not returned or filtered out by the client. So then not returning them from the server seems to be a sane approach that will also potentially save server some processing. Even if spec can't or chosen to not explicitly disallow that.

> Also, if your interpretation was true, the idea from #96 to return the "Create Table of Contents" action when the curser / requested range is on the first line, would not be allowed then.

I think that idea is a bit strange anyway.

**Comment by artempyanykh** [comment]
> I think that idea is a bit strange anyway

@rchl I'm open to other ideas 🙂 It's important though that the solution should work in all editors/LSP clients in a sane way.

**Comment by artempyanykh** [comment]
I found some time to check the behavior in other editors; unfortunately, neither nvim, nor helix, nor emacs/eglot provide code action kind, trigger kind when requesting code actions. Basically, whatever the spec has to say about `only?` in code action request, the actual behavior is idiosyncratic to a particular editor/LSP client.

> I'm still planning to filter out non-quickfix code actions in st regardless.

👍
