### ISSUE TITLE
Nix Support

### ISSUE THREAD

**Issue by RobWalt** [artempyanykh/marksman#92]
I would like to use marksman on my nix based system, but I don't have any experience with packaging so far and failed when I tried to do so for marksman.

I'll assist as good as I can if someone else wants to try it out.

**Comment by stasjok** [comment]
I managed to package it. You can test it if you want: NixOS/nixpkgs/#193682.

**Comment by RobWalt** [comment]
It just got merged! 🎉 Thanks and congrats to @stasjok! I'll take care of the install docs in the README here if that's ok for you.
