### ISSUE TITLE
ARM Linux support

### ISSUE THREAD

**Issue by cor** [artempyanykh/marksman#98]
It would be nice if ARM linux binaries could be provided

**Comment by artempyanykh** [comment]
Thanks for raising this @cor ! I use GitHub runners to build releases on CI. To build for ARM Linux one of the following should happen:
1. someone figures out how to setup a cross-compiling toolchain to build and publish aarch64 binaries from x86 host,
2. someone donates an aarch64 machine to use as a self-hosted runner,
3. github adds aarch64 managed runners.

The timeline for neither of these is in any way clear ATM, but I'm def. open to build for more arches.

**Comment by artempyanykh** [comment]
As I recently learned, dotnet tool can cross-compile and link an aarch64 macOS binary from an x64 host (this is what we do to publish universal binaries for MacOS from standard GH x64 macOS runners).

Perhaps dotnet can do the same thing for Linux?

**Comment by Qinka** [comment]
I think you can use buildkit and binfmt, see https://docs.docker.com/build/building/multi-platform/ . Build the binary in the docker, and copy the binary outside.  it use qemu-user.

**Comment by artempyanykh** [comment]
@Qinka thanks for chiming in!

Actually, dotnet CLI can cross-compile and cross-link. For instance, I just ran the following on my x64 linux box
```
make publish RID=linux-arm
```

Copied the produced binary to a raspberry pi and it ran just fine.

---

All what's required to produce pre-built binaries for ARM is for someone to adjust [release.yml](https://github.com/artempyanykh/marksman/blob/main/.github/workflows/release.yml) to run `publishTo` task with `linux-arm64` (and maybe `linux-arm`) RID on x64 GH runner.
